### ISSUE TITLE
the pretrained model cannot use

### ISSUE THREAD

**Issue by lgcy** [DVLP-CMATERJU/RectiNet#1]
the pretrained model weight name is different from the model define, so the model can not load the weight

**Comment by hmrishavbandy** [comment]
Hi,
More details about the error that you are encountering? Most probably a screenshot or a copy of the error log?

**Comment by lgcy** [comment]
> Hi,
> More details about the error that you are encountering? Most probably a screenshot or a copy of the error log?

![1595916768311](https://user-images.githubusercontent.com/26407517/88626139-afdb7880-d0dc-11ea-862c-e153b9b65b53.jpg)

**Comment by lgcy** [comment]
the error log is:
    Missing key(s) in state_dict: "unet1.down_conv0.0.weight", "unet1.down_conv0.0.bias"...so on

**Comment by hmrishavbandy** [comment]
Will be updating the repository.

**Comment by hmrishavbandy** [comment]
Solved in most recent commit.
