### ISSUE TITLE
utils_model does not have any object named initialize_weights

### ISSUE THREAD

**Issue by testerpce** [DVLP-CMATERJU/RectiNet#5]
When trying to run train.py I am getting the error that  cannot import initialize_weights. On checking the utils_model.py file in utils folder I am finding that there is no function or class named initialize_weights. Is this an error in the branch or something?

**Comment by hmrishavbandy** [comment]
Hi, thank you for pointing that out. I have added the functionality. Please recheck if everything runs.

**Comment by testerpce** [comment]
thanks
