### ISSUE TITLE
How many epochs of training did you get the best model

### ISSUE THREAD

**Issue by ARnnn** [DVLP-CMATERJU/RectiNet#7]
I have trained 100 epochs according to your code, but the result is not ideal. How many epochs have you trained and got the best result?

**Comment by hmrishavbandy** [comment]
Apologies for the delayed response. Since the code was released some time back, I do not perfectly remember the number but it should ideally settle down by 200 epochs.

**Comment by Testhjf** [comment]
how many train data sets ,you trained ,thanks!
