### ISSUE TITLE
Question about Models

### ISSUE THREAD

**Issue by copperhand** [DVLP-CMATERJU/RectiNet#9]
Hi! 
I have tried to run your code, but after training the data, I have some questions about the Models.
The project provieded two model, the first one is in the model.py and the second one is in the model_pred.py. When I tried to run the predict.py, it asserted missing keys in state_dict. I checked the code and found different models used in train.py and predict.py.
I guess the code following is trying to import the intersection of two state dict;
File "predict.py", line 108, "state_dict = {k: v for k, v in state_dict.items() if k in model_dict}"
 I can predict with the pre_trained model provided, but failed in the model trained by myself. This Block may not work well.

I want to know the difference between the two models and why the project use two model for train and prediect respectively?

**Comment by copperhand** [comment]
Part of the error log is following:
Traceback (most recent call last):
  File "predict.py", line 181, in <module>
    predict(model_path,img_path,save_path,scan_path,check,filename)
  File "predict.py", line 134, in predict
    model.load_state_dict(state_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.down_conv0.0.weight", "module.down_conv0.0.bias", "module.down_conv0.1.weight", "module.down_conv0.1.bias", "module.down_conv0.1.running_mean", "module.down_conv0.1.running_var", "module.down_conv0.4.weight", "module.down_conv0.4.bias", "module.down_conv0.5.weight", "module.down_conv0.5.bias", "module.down_conv0.5.running_mean"...

**Comment by hmrishavbandy** [comment]
Hi, the issue is that while training my network architecture was a single chunk of code and not modular in nature as it is now. So the saved weights are loadable only from that single chunk of code that I have deposited in model_pred.py. I later reformatted the code and created model.py
